### ISSUE TITLE
Unable to access files

### ISSUE THREAD

**Issue by yauyenching** [AndreAle94/moneywallet#100]
On OnePlus7T/Android 10, i'm unable to see any files at all in my external storage despite giving permission to read and write files. This makes it hard to restore backups which is highly inconveniencing!

**Comment by nicob0210** [comment]
Yes, I have the same problem, before I made a backup that now I can't restore and I can't even do one because it says that my memory is empty

**Comment by AndreAle94** [comment]
This may be related to changes of storage api starting from Android 10.
More details are available here: https://developer.android.com/training/data-storage#scoped-storage

I'll try to fix this when i have some free time.

**Comment by AndreAle94** [comment]
The issue should be (temporary) solved with v4.0.5.5

**Comment by nicob0210** [comment]
Thanks bro your app is the best for managing my budget and now without I'm
lost😂
(Also I think you're Italian too)

**Comment by nicob0210** [comment]
And also, when will you update the v4.0.5.5?

**Comment by AndreAle94** [comment]
The release is already available on Github (release section). On F-Droid you have to wait until their automated system builds the app (two/three days). The PlayStore release will be published only when i'm sure that the bug is solved.

**Comment by bendaf** [comment]
I've tried out the new version (4.0.5.6) on Android 10 and the export works well. I would suggest to release it on Google play, since it is better than the old one.

**Comment by AndreAle94** [comment]
@bendaf thank you, i'll update the PlayStore release as soon as possible!

**Comment by cauerego** [comment]
looks like this issue is back for Android 11!
