### ISSUE TITLE
[support] Delete entries

### ISSUE THREAD

**Issue by nr458h** [AndreAle94/moneywallet#101]
As the year reached its end I would like to clear all balance entries and only keep the accounts, categories, persons ...
Is there a way to do so or do I need to start from scratch.

(I do have root access probably I can delete some app files?)

Thanks for help and the great app

Merry Christmas everyone

**Comment by AndreAle94** [comment]
No, there is no way to do this. The only action you can do is to export the old data (do always a native backup) and clean the app data. This will force you to restart from an empty database.

By the way, if you are familiar with SQL, you can try to drop manually the content of all the tables except for wallets, categories, people and so on, but keep in mind that a small error can easily make the app unstable.

**Comment by nr458h** [comment]
thanks for the feedback. As there is nothing to do left. I will close this one
