### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by bendaf** [AndreAle94/moneywallet#106]
It would be great to have the app in Hungarian language also.

**Comment by bendaf** [comment]
@AndreAle94 I will work on Hungarian translation, if it's ok for you.

**Comment by fbenda** [comment]
@AndreAle94 Do you mind, if I translate the app to Hungarian?

**Comment by AndreAle94** [comment]
Hi @bendaf and @fbenda, sure thankyou! P.R. are welcome!

**Comment by bendaf** [comment]
Cool, thanks :). (This is my private profile)

**Comment by bendaf** [comment]
Hi @AndreAle94! I would love to contribute to this repo and also have a few improvement ideas. What do you think which issues are the most important ones, with which I could start to improve the app? If I add my ideas as new issues would you consider them also and accept pull requests for them if they fit well to the app?

**Comment by AndreAle94** [comment]
Hi @bendaf, yes all ideas and PRs are very welcome. Now i'm very busy and i have no time to dedicate to this app. The most important bug to fix is issue #98 but i'm not able to replicate it (maybe a device manufacturer related issue).

**Comment by bendaf** [comment]
I'm trying to reproduce #98 but I was not able to do so yet. I think I will close this issue.
