### ISSUE TITLE
Exclude internal transfers from budgets

### ISSUE THREAD

**Issue by wandertaker** [AndreAle94/moneywallet#118]
Hello,
I'd like to propose a change to the behaviour of budgets.
With the current implementation all transfers are added to budgets if they are configured for income or expenses.
While this makes sense to me if the budged is configured for a single wallet it's not very helpful with budgets for multiple wallets, at least for transfers between these wallets.

Therefore I would like to change the current implementation and **exclude all transfers from budgets which are between wallets which belong to the budget**.

**Example:**

I have three wallets

1. Cash
2. Bank Account
3. Savings Account

and a budget for expenses from the cash and the banking account.
Now if I withdraw money from my banking account, e.g. add a transfer money from the bank account to my my cash account.
With the current implementation this is added as an expense to my budget.
In my opinion this doesn't make sense because in total there is no loss to the wallets of the budget.
With the new implementation this transfer would not be added to the budget.
But if I transfer money from my banking account to my saving account this would be added to the budget, because the savings account does not belong to the budget. 

What do you think about this idea?
This would also solve one of the problems from #44.
I'd like to implement this feature if you're ok with this.

**Comment by AndreAle94** [comment]
Hello,
you are right, this should be handled differently.

Sure! thank you :)

**Comment by Mattrazol** [comment]
@wandertaker I've noticed that you have made a pull request to fix this. Could this fix be applied also to the Overview view because I think it has the same behavior there too. See the issue #137

**Comment by wandertaker** [comment]
Hi @Mattrazol 
I haven't looked into it but I think the same fix could be applied for #137 as well. It's basically just another filter statement for the SQL query and the overview view probably works in a similar way.
Unfortunately the project is only maintained sporadicly and I did not get any feedback regarding #125 so far. I'll wait for this before I open another PR.
