### ISSUE TITLE
Cant type $82.49

### ISSUE THREAD

**Issue by inpharmaticist** [AndreAle94/moneywallet#159]
Keeps changing to 82.48.

**Comment by ralphocdol** [comment]
I'll back this up, some decimal amount keeps rounding down/up

**Comment by GhitzaSchnitza** [comment]
Can't type 77.99 and 70.46 Keeps reverting to 77.98 and 70.45 respectively

**Comment by ivanlewin** [comment]
I had this same error a few times, I think it has something to do with adding decimals in currency exchange. I would suggest making a backup, cleaning the app data and restoring it, it worked for me

**Comment by AndreAle94** [comment]
I've just merged the pull request that should fix this issue, feel free to reopen this issue if the problem persists in the next release
