### ISSUE TITLE
ledger, hledger, and cone

### ISSUE THREAD

**Issue by cauerego** [AndreAle94/moneywallet#167]
there's one critical aspect of being open sourced that was missed here... using open standards.

the standard for personal finance and accounting is the ledger.

and the best app i could find to use it on android for now are cone and ledger on termux.

https://cone.tangential.info/wiki/Mobile-ledgers/

not sure why i didn't do it before, but i'm glad i did it before starting to use this otherwise little nice app.

so i'm probably not looking back.

cheers! 😘

**Comment by AndreAle94** [comment]
Hi, this app has been designed to be modular: you can implement additional data import and export formats as you wish (just take a look here: https://github.com/AndreAle94/moneywallet/tree/master/app/src/main/java/com/oriondev/moneywallet/storage/database/data).

Honestly I am not interested in implementing it, I am however available to integrate it in case someone wants to develop it.

**Comment by cauerego** [comment]
there's a thin balance to keep a piece of software open and built collaboratively rather than competing. for two opposing instances:

- there's phonograph, a huge music player reference, filled with forks and all of them are somehow broken in android 10 if you're using an SD card (which is supposedly one of its big usage cases today).
- and then there's termux. for whatever reason, devs collaborate to build the one termux and make it always better.

imho, embracing new standards that don't offer anything better than the one ledger standard falls into the first category. and it's actually a detrimental feature.

but i criticized this enough.

let me also state that i fully appreciate how you moved from closed source into opening it up! it's very inspiring and a unique movement on its own. it's also the reason why i even bothered to give all this feedback.

hope you'll appreciate it someday but, even if not, i'll be fine! ;D
