### ISSUE TITLE
Expense with a minus sign increases the total. 

### ISSUE THREAD

**Issue by angirassahu** [AndreAle94/moneywallet#169]
We add expense with minus sign then instead of decreasing the capital it increases it this is problematic as sometimes the whole total is messed up there is also other issue most of the time the total is measured up because the wallet balance in the slide menu is not updated sometimes please look into it

**Comment by AndreAle94** [comment]
Duplicate of #93

**Comment by angirassahu** [comment]
This is an amazing app it helps me a lot.
