### ISSUE TITLE
Recurrences page, tablet, portrait mode: first item partially visible

### ISSUE THREAD

**Issue by Nelis1846** [AndreAle94/moneywallet#207]
hello again :)

first i ( again ) want to express my gratitude to the writer of this app because this app is of VERY high value to me. i use it every day for all my finances.

but there is an issue that is very annoying to me: when i navigate to the recurrences page, ( tablet, portrait mode ), the top item is almost entirely hidden below the tabs where i can choose between "transactions" and "transfers". this issue only occurs in portrait mode.

i would strongly appreciate it if someone can fix it because i have to use this tablet in portrait mode because some apps do not work well with landscape mode or they switch to portrait mode because some activities do not support landscape mode :(

thank you :)

**Comment by holysh1t** [comment]
Is there a way, you can screenshot the issue?

**Comment by Nelis1846** [comment]
![Screenshot_20211104-134703](https://user-images.githubusercontent.com/47606851/140316614-3a954308-860b-4f79-b0c8-1ea3a7dd37f4.png)

( i obviously had to hide my personal data )

**Comment by Nelis1846** [comment]
![moneyWallet_issue](https://user-images.githubusercontent.com/47606851/140316825-d0c802b1-5d7c-41ac-b4e8-c145fed40501.png)

**Comment by holysh1t** [comment]
Can you also specify which device you are using?

**Comment by Nelis1846** [comment]
> Can you also specify which device you are using?

Teclast P20HD

**Comment by radusalagean** [comment]
https://github.com/AndreAle94/moneywallet/pull/209 should fix it.
