### ISSUE TITLE
[Question] Overview and Categories

### ISSUE THREAD

**Issue by trmendes** [AndreAle94/moneywallet#21]
I'm using the F-droid version of your app and I must say: It is a great app. Thanks a lot.

When you go to the categoires you have the system tab with "Credit, Credit paid, debt, tax, transfer, etc". How do I do to use them? I would like to "tag" a transition I made as "cash" or "credit card" or "debit card" or "transportation card". Is that the idea behind the system tab under the categories?!

Sorry if I had to open an issue to ask you a question.

**Comment by AndreAle94** [comment]
Thanks! No, system categories are designed to be used only by the application to correctly categorize certain situations (a transfer, a debt, ...). If you want to use different payment methods, the best thing to do is create different wallets (cash, back accounts, ...).
