### ISSUE TITLE
Feature Request: add support for crypto currencies

### ISSUE THREAD

**Issue by saloniamatteo** [AndreAle94/moneywallet#213]
Hello,
it would surely be a nice addition to MoneyWallet to add support for crypto currencies, like Monero (XMR), Bitcoin (BTC), Ethereum (ETH) and so on.

I suggest either adding these major ones, or add a way to add a custom (crypto) currency

**Comment by allan-null** [comment]
Just go to `Menu > Utilities > Manage currencies`, and you can set up any currency you want! I myself have 3 different kinds of cryptocurrencies set.

**Comment by saloniamatteo** [comment]
Didn't know, thanks!
