### ISSUE TITLE
Toman 

### ISSUE THREAD

**Issue by herotux** [AndreAle94/moneywallet#26]
We have a currency in Iran called Toman Where the one zeros are removed from the Rials.
Toman is the unofficial currency but common currency in the country
Toman = تومان
10 Rial = 1 Toman
25000 Rial = 2500 Toman
 please add this currency .
thanks
:rose:

**Comment by AndreAle94** [comment]
As already said, this currency will not be added to the default currencies because it is not an official currency. With commit ecedd34 the user will be able to create and manage his own currencies, so you will be able to add it from the preference screen.

**Comment by herotux** [comment]
Thanks alot
