### ISSUE TITLE
Restore from JSON file imports a subset of data

### ISSUE THREAD

**Issue by AkashRajpurohit** [AndreAle94/moneywallet#285]
Faced this issue #177 so had to uninstall the app.
I had a backup from last 2 days so uninstall and restore from backup made sense but when I am trying to restore on the new app it is only restoring a very small subset of data.

Have verified that the database.json file have data from the most recent transaction but the restore is failing to pull the whole data.

Is there any way I can either tweak the database.json file manually for the restore to complete properly?

Any help is appreciated.

**Comment by Kayetil** [comment]
> Столкнулся с проблемой [№ 177](https://github.com/AndreAle94/moneywallet/issues/177) , поэтому пришлось удалить приложение. У меня была резервная копия за последние два дня, поэтому удаление и восстановление из резервной копии имело смысл, но когда я пытаюсь восстановить новое приложение, восстанавливается только очень небольшая часть данных.
> 
> Убедились, что в файле data.json есть данные из самой последней транзакции, но при восстановлении не удается получить все данные.
> 
> Можно ли как-нибудь вручную настроить файл data.json, чтобы восстановление завершилось правильно?
> 
> Любая помощь приветствуется.

Привет

**Comment by AkashRajpurohit** [comment]
Figured out the issue
