### ISSUE TITLE
[bug] cant set specific initial amount

### ISSUE THREAD

**Issue by nr458h** [AndreAle94/moneywallet#32]
When I try to edit the initial amount of an banking account I m not able to set it to the falue: 4362,65 when I press equal it goes back to the account page and shows 4362,64 ... 
Also changing the amount save it and then try ti set it to the falue I and up with 4362.64 🤣

**Comment by AndreAle94** [comment]
This is a rounding issue of the calculator, thanks for letting me know about it. 
You can bypass it using an amount of 4362,655 until the bug is fixed.
