### ISSUE TITLE
Feature Request: Quick add widgets

### ISSUE THREAD

**Issue by j6s** [AndreAle94/moneywallet#35]
It would be nice to have a widget that allows you to quickly add expenses. This would basically be a shortcut to the new expense screen in the app (since shortcuts don't seem to be a thing in android anymore).

What I imagine is similar to how 'My budget book' handles it: A simple icon that acts as a shortcut (see screenshots)

![photo_2019-01-05_11-01-11](https://user-images.githubusercontent.com/3374170/50723094-3da9da00-10d9-11e9-91df-f797e465a2ea.jpg)
_Clicking the red minus icon jumps straight to this screen:_

![photo_2019-01-05_11-01-13](https://user-images.githubusercontent.com/3374170/50723099-4c908c80-10d9-11e9-912e-f6656efa4cea.jpg)

**Comment by AndreAle94** [comment]
Closed with 678e775
