### ISSUE TITLE
[Feature Request] Transfers

### ISSUE THREAD

**Issue by GreenDragon527** [AndreAle94/moneywallet#37]
Existing transfer show in both source and destination wallets. New transfers only show in source accounts. Can this feature be redone?

**Comment by AndreAle94** [comment]
I did not understand what you mean: currently, when a transfer is inserted, a transaction is entered as income and another one as expense. If this does not happen in your case, it's a bug. If instead your idea is to enter only one transaction, this is not possible with the current architecture.

**Comment by GreenDragon527** [comment]
Oh many apologies. I tried to test again and noticed the date was off, set in the future by a day, so I'm assuming it appeared in the source as pending and did not show up in the destination wallet because the transaction did not yet occur. Thanks much!
