### ISSUE TITLE
[bug] app crashes after setting custom theme colors

### ISSUE THREAD

**Issue by nr458h** [AndreAle94/moneywallet#41]
Hi, i face a really bad bug. I was playing with the settings and also changed the main color or the theme color to a custom value.
After applying the change the app keeps continually crashing and i am not able to reset it because i can't enter the app anymore.
Dalvik & cache cleaning did not work. 

I do have root access so it possible you also can point me where to go to change this in the database.

Help is highly appreciated, as I didn't perform a backup until now :(

**Comment by AndreAle94** [comment]
Are you on the last version? If yes, please provide here the stacktrace of the crash, if not, it may be related to a bug that has been already solved with commit 743ee0c . In the last case, you should update to fix the issue.

**Comment by nr458h** [comment]
Thanks update fixed it - but there was no update shown in f-droid. After installing it from github the newer versions are also shown in f-droid.

Thanks!
