### ISSUE TITLE
Decimals rounded up in big numbers

### ISSUE THREAD

**Issue by beljebuzz** [AndreAle94/moneywallet#62]
Hi, I tried to enter 794197.96 as the initial balance of a new account but it is rounded to 794198.00 which is not accurate enough to allow a clean accounting. The currency is CRC (1/600 : USD).

Thanks

**Comment by FoseFx** [comment]
~~It looks like~~ the app starts rounding at 7 digits.
I think I tracked it down to this [line][bad-line].

[Java Docs][dec32]:
> A MathContext object with a precision setting matching the IEEE 754R Decimal32 format, 7 digits, and a rounding mode of HALF_EVEN, the IEEE 754R default.

I assume changing it to [DECIMAL64][dec64] (16 digits) would be enough, but [UNLIMITED][unl] would be safe for all custom currencies. However I am not sure what negative side-effects such a change would trigger.

[bad-line]: https://github.com/AndreAle94/moneywallet/blob/0515e94f04bfdeb45c8f7ed513c0aa08f064279d/app/src/main/java/com/oriondev/moneywallet/utils/EquationSolver.java#L187

[dec32]: https://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html#DECIMAL32

[dec64]: https://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html#DECIMAL64

[unl]: https://docs.oracle.com/javase/7/docs/api/java/math/MathContext.html#UNLIMITED
