### ISSUE TITLE
No changes with wallet money after paying debts

### ISSUE THREAD

**Issue by mohammadsyafeeq** [AndreAle94/moneywallet#65]
At the debts section, after I input some "pay", I notice my wallet money, or total money doesn't change at all.

MoneyWallet 4.0.5
Android 6.0.1

**Comment by wandertaker** [comment]
I have the same issue and have examined it more closely.
The wallet money as well as the total money is changed correctly in the database but the UI is not notified to update the values.
The PR linked above fixes this issue.
