### ISSUE TITLE
Add Privacy Policy.

### ISSUE THREAD

**Issue by HarryHeights** [AndreAle94/moneywallet#70]
A privacy policy is invaluable for this kind of project. You seem not to have one. I could help create one for you. If you mind.

**Comment by AndreAle94** [comment]
I have just added a basic privacy policy that should be enough given that i do not collect any valuable personal information. If you think that it can be improved, please open a pull request and i'll evaluate your changes.

**Comment by HarryHeights** [comment]
I just checked it out. It's perfect.
