### ISSUE TITLE
[UX] Model List Swap description and category

### ISSUE THREAD

**Issue by FoseFx** [AndreAle94/moneywallet#89]
Great project!

The heading of each Card is the first element a user looks at.
That's why I think it should contain the description of each model.

I personally am very confused every time I want to use a model.

|Currently|My proposal|
|-----------|-----------------|
| ![model](https://user-images.githubusercontent.com/22842759/68408033-df300b00-0184-11ea-96b0-0d9656ade18e.jpg) | ![model-swap](https://user-images.githubusercontent.com/22842759/68408053-e820dc80-0184-11ea-8131-8e68a222fd32.png) |

The icon should probably stay the same.
This way the user can quickly identify the category the item is in without having to read the subheading at all.

**Comment by AndreAle94** [comment]
Well, this can be merged if you think the users will appreciate it. By the way, a user can add a model without a description (it is not mandatory): in this case the primary textview will be empty resulting in a bad UI. Maybe we can check it first and, if a description is found, invert the two fields as you have proposed. What do you think?

**Comment by FoseFx** [comment]
> Maybe we can check it first and, if a description is found, invert the two fields as you have proposed

I agree and start working on it.

**Comment by FoseFx** [comment]
PR [updated](https://github.com/AndreAle94/moneywallet/pull/91/commits/b9ad7c89dd825add0bb9060a7d2a8ac5eae1a388)
