### ISSUE TITLE
Recurrences can not be edited

### ISSUE THREAD

**Issue by uli-on** [AndreAle94/moneywallet#90]
Once set up/saved, you can't edit recurrences. Please, can that be amended?

**Comment by AndreAle94** [comment]
The app has been designed with the capability of supporting data synchronization with a (possible future) backend. Allowing the user to edit recurrent event (like recurrent transactions and transfers) will broke the synchronization algorithm. This is the main reason a user cannot edit a scheduled recurrence. By the way, you can simply delete it and create a new one.
