### ISSUE TITLE
Wallet Balance incorrect

### ISSUE THREAD

**Issue by m82947** [AndreAle94/moneywallet#93]
Expenses are counted as income.
Tried to export the wallet, reinstall the latest version and restore the backup, no success.

Would love to use this app, please help me and fix this.

![Screenshot_20191111-221921](https://user-images.githubusercontent.com/22917584/68621993-60fb9d80-04d1-11ea-8c44-13305e9a6fee.jpg)
![Screenshot_20191111-221928](https://user-images.githubusercontent.com/22917584/68622006-6658e800-04d1-11ea-9955-101601be99fc.jpg)

**Comment by AndreAle94** [comment]
Hello, i'm not able to replicate this bug on my device. Can you please give me more details about your device (app version, playstore or f-droid, android version ...) and maybe attach the backup file that generates this wrong output (the one used to produce the screenshots, not your personal data) ?
Thank you.

**Comment by m82947** [comment]
App version: app-floss-osm-release-v4.0.5.3-68.apk (latest release from github)
Device: SM-G955F on Android 7.0
[backup_2019-11-13_15:35:26.mwbx.zip](https://github.com/AndreAle94/moneywallet/files/3841691/backup_2019-11-13_15.35.26.mwbx.zip)

Thanks for your help!

**Comment by AndreAle94** [comment]
Well, you just simply needs to enter the money amount without the sign. The app calculates the total using the information related to the selected category. In this case, you entered an expense with a negative amount so the app will subtract a negative number resulting in a sum.

**Comment by m82947** [comment]
LOL

**Comment by m82947** [comment]
Thanks man...
