### ISSUE TITLE
Automatic backups once a day or week

### ISSUE THREAD

**Issue by TobiasDev** [AndreAle94/moneywallet#97]
I would love to see a setting where the app can make an automatic backup every day, week or month. All I mean is that rather than me going in and pressing the button to create a backup it does it by itself on a recurring time.

With that I could use it togheter with NextCloud automatic folder sync to always make sure I have a recent backup if I where to lose my phone.

Eg.
1. The app automatically makes a backup everyday at 6 am.
2. That backup is placed in a folder I have choosen myself
3. I turn on, in my NextCloud apps so it always takes anything saved in that folder and uploads it to my cloud storage.
4. Now I always have a backup if I were to lose my phone

**Comment by AndreAle94** [comment]
If i understand correctly, this feature is already there, you can enable auto backups in the same screen where you create (and restore) backup files. There is an icon inside the toolbar.

**Comment by TobiasDev** [comment]
Oh, sorry! I missed that button for some reason... My mistake!
